# Generated by Django 2.2.6 on 2019-10-13 22:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('abilities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None)),
                ('against_bug', models.FloatField(null=True)),
                ('against_dark', models.FloatField(null=True)),
                ('against_dragon', models.FloatField(null=True)),
                ('against_electric', models.FloatField(null=True)),
                ('against_fairy', models.FloatField(null=True)),
                ('against_fight', models.FloatField(null=True)),
                ('against_fire', models.FloatField(null=True)),
                ('against_flying', models.FloatField(null=True)),
                ('against_ghost', models.FloatField(null=True)),
                ('against_grass', models.FloatField(null=True)),
                ('against_ground', models.FloatField(null=True)),
                ('against_ice', models.FloatField(null=True)),
                ('against_normal', models.FloatField(null=True)),
                ('against_poison', models.FloatField(null=True)),
                ('against_psychic', models.FloatField(null=True)),
                ('against_rock', models.FloatField(null=True)),
                ('against_steel', models.FloatField(null=True)),
                ('against_water', models.FloatField(null=True)),
                ('attack', models.IntegerField(null=True)),
                ('base_egg_steps', models.IntegerField(null=True)),
                ('base_happiness', models.IntegerField(null=True)),
                ('base_total', models.IntegerField(null=True)),
                ('capture_rate', models.IntegerField(null=True)),
                ('classfication', models.CharField(max_length=100, null=True)),
                ('defense', models.IntegerField(null=True)),
                ('experience_growth', models.IntegerField(null=True)),
                ('height_m', models.FloatField(null=True)),
                ('hp', models.IntegerField(null=True)),
                ('japanese_name', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('percentage_male', models.FloatField(null=True)),
                ('pokedex_number', models.IntegerField(primary_key=True, serialize=False)),
                ('sp_attack', models.IntegerField(null=True)),
                ('sp_defense', models.IntegerField(null=True)),
                ('speed', models.IntegerField(null=True)),
                ('type1', models.CharField(max_length=100, null=True)),
                ('type2', models.CharField(max_length=100, null=True)),
                ('weight_kg', models.FloatField(null=True)),
                ('generation', models.IntegerField(null=True)),
                ('is_legendary', models.BooleanField(null=True)),
            ],
        ),
    ]
