# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.postgres.fields import ArrayField

# Create your models here.
class Pokemon(models.Model):
    abilities = models.CharField(max_length=500, null=False,default="")
    against_bug = models.CharField(max_length=500, null=False,default="")
    against_dark = models.CharField(max_length=500, null=False,default="")
    against_dragon = models.CharField(max_length=500, null=False,default="")
    against_electric = models.CharField(max_length=500, null=False,default="")
    against_fairy = models.CharField(max_length=500, null=False,default="")
    against_fight = models.CharField(max_length=500, null=False,default="")
    against_fire = models.CharField(max_length=500, null=False,default="")
    against_flying = models.CharField(max_length=500, null=False,default="")
    against_ghost = models.CharField(max_length=500, null=False,default="")
    against_grass = models.CharField(max_length=500, null=False,default="")
    against_ground = models.CharField(max_length=500, null=False,default="")
    against_ice = models.CharField(max_length=500, null=False,default="")
    against_normal = models.CharField(max_length=500, null=False,default="")
    against_poison = models.CharField(max_length=500, null=False,default="")
    against_psychic = models.CharField(max_length=500, null=False,default="")
    against_rock = models.CharField(max_length=500, null=False,default="")
    against_steel = models.CharField(max_length=500, null=False,default="")
    against_water = models.CharField(max_length=500, null=False,default="")
    attack = models.CharField(max_length=500, null=False,default="")
    base_egg_steps = models.CharField(max_length=500, null=False,default="")
    base_happiness = models.CharField(max_length=500, null=False,default="")
    base_total = models.CharField(max_length=500, null=False,default="")
    capture_rate = models.CharField(max_length=500, null=False,default="")
    classfication = models.CharField(max_length=500, null=False,default="")
    defense = models.CharField(max_length=500, null=False,default="")
    experience_growth = models.CharField(max_length=500, null=False,default="")
    height_m = models.CharField(max_length=500, null=False,default="")
    hp = models.CharField(max_length=500, null=False,default="")
    japanese_name = models.CharField(max_length=500, null=False,default="")
    name = models.CharField(max_length=500, null=False,default="")
    percentage_male = models.CharField(max_length=500, null=False,default="")
    pokedex_number = models.CharField(max_length=500, primary_key=True, null=False,default="")
    sp_attack = models.CharField(max_length=500, null=False,default="")
    sp_defense = models.CharField(max_length=500, null=False,default="")
    speed = models.CharField(max_length=500, null=False,default="")
    type1 = models.CharField(max_length=500, null=False,default="")
    type2 = models.CharField(max_length=500, null=False,default="")
    weight_kg = models.CharField(max_length=500, null=False,default="")
    generation =  models.CharField(max_length=500, null=False,default="")
    is_legendary = models.CharField(max_length=500, null=False,default="")
